### PR TITLE
Upgrade the plugin to be compatible with C3 r368.2

### PR DESCRIPTION
**Pull request by marc-n-dream**
For now draft while digging deeper into the plugin / type aspect and how to make optimal use of them.

### CODE REVIEW

**Comment by laurentndream** [comment]
Anything I can do on my side to help? Maybe testing?

**Comment by Psychokiller1888** [comment]
Great job!

But it's already done here: https://github.com/AirConsole/airconsole-construct3/tree/1.8.0.0

**Comment by Psychokiller1888** [comment]
As I stated on Discord, it needs feedback from community to merge. Linus wrote me to fix the plugin started function, the rest is working, at least should :-)

**Comment by marc-n-dream** [comment]
@Psychokiller1888 I did honestly overlook that branch due to the `not maintained anymore` message. Is that not correct then?

I would like to understand more on the specific use cases / needs that some of the actions and conditions cover in this pluing but to keep thiings simple: Is there a strong reason for that plugin started action from the construct 3 side or a special use case that otherwise creates problems?

**Comment by Psychokiller1888** [comment]
I updated everything for the BMW launch and since then I am in touch with Linus (8bit fiesta), I've asked to remove the 'not maintained' but it wasn't done by your team. Same for the guides. The plug-in started is needed because of the flow of how C2 and C3 load, if you start AC without it, C2/3 is not yet ready to get the signal back from AC and you fail the init

**Comment by Psychokiller1888** [comment]
I propose to merge 1.8.0.0 to master as soon as Linus gets time to test and confirm the working flow.

**Pull request closed without merging**
